### ISSUE TITLE
Suggest including input gene(s) in output list of orthologs

### ISSUE THREAD

**Issue by jrsjrs** [intermine/go-intermod#2]
I searched for ADH5 (human) and got back 15 human genes, but ADH5 wasn't among them meaning that I couldn't directly compare the annotations for human ADH5 to its orthologs in the other species.  I think the input gene(s) that return orthologs from the search should also be included in the list of "orthologs" that are returned.  (I would say that a gene that doesn't return orthologs should not be included in the result set unless it was listed in a "no orthologs" section so that users could choose to include it in the analysis if they wanted to, but that's another question.)  But in any case, if I enter human ADH5 and get orthologs back from the other species I'm probably going to want to see the results for human ADH5 as well.

**Comment by julie-sullivan** [comment]
Good point! @rachellyne mentioned that too I think.

**Comment by yochannah** [comment]
This should now be present in the live tool - screenshot of ADH5 below. The three results are comprised of the original gene and the orthologs, but not the paralogs.
![image](https://cloud.githubusercontent.com/assets/9271438/16312123/422b45d4-396b-11e6-9b0f-6e936e6022df.png)
