### ISSUE TITLE
Input of Yeast and TFC3 does not return anything.

### ISSUE THREAD

**Issue by kkarra** [intermine/go-intermod#3]
I am having a hard time understanding the search mechanism.  If this is a 'Orthology Search' tool and not a 'Gene Search' tool  i.e any gene input is going to be checked to be a human ortholog of some other organism, then, any non-human gene input will not work, is that right? 

Yeast and ACT1 returns nothing either.  

I searched humanmine for ACT1 thinking there has to be a human gene named ACT1, but, it only appears as a synonym of  TRAF3IP2.

SOX18 returns results, although there is no SOX18 gene in yeast. There are yeast genes with SOX18 as human ortholog.

I found Julie's email where she describes how the code will work and that it needs to be made clear to the user. Perhaps thats what it is..

**Comment by yochannah** [comment]
I think this should be fixed now - we're accepting genes of any input organism now, not just human. Screenshot:

![image](https://cloud.githubusercontent.com/assets/9271438/16337279/0b0bc7b2-3a0c-11e6-9d7c-0865d09ac2a2.png)
